<?php

/**
 * @file
 * Contains json_field.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function json_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the json_field module.
    case 'help.page.json_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a JSON field, formatter and views integration.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function json_field_theme() {
  $theme = [];

  return $theme;
}
